name: ðŸ”¨ Release Test

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.go"
      - "**.mod"
  workflow_dispatch:

jobs:
  release-test-mac:
    runs-on: macos-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: release test
        uses: projectdiscovery/actions/goreleaser@v1
        with:
          args: --config=.goreleaser/mac.yml
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-test-linux:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: "Check out code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x

      # todo: musl compatible?
      - name: Install Dependences
        run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu

      - name: release test
        uses: projectdiscovery/actions/goreleaser@v1
        with:
          args: --config=.goreleaser/linux.yml
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-test-windows:
    runs-on: windows-latest-8-cores
    steps:
      - name: "Check out code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x

      - name: release test
        uses: projectdiscovery/actions/goreleaser@v1
        with:
          args: --config=.goreleaser/windows.yml
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
